name: run

on:
  workflow_call:
    inputs:
      FORCE_REFRESH:
        type: boolean
        default: false
      INPUT:
        type: string
        required: true
      OUTPUT:
        type: string
        required: true

jobs:
  fetch_uuids:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: checkout name fetcher 
        uses: actions/checkout@v3
        with:
          repository: MCResourcePile/name-fetcher
          path: scripts/name-fetcher
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ${GITHUB_WORKSPACE}/scripts/name-fetcher/requirements.txt
      
      - name: execute py script
        if: ${{ inputs.FORCE_REFRESH }} != true
        run: |
          python ${GITHUB_WORKSPACE}/scripts/name-fetcher/run.py ${{ inputs.INPUT }} ${{ inputs.OUTPUT }}
      
      - name: execute py script (forced refresh)
        if: ${{ inputs.FORCE_REFRESH }} == true
        run: |
          python ${GITHUB_WORKSPACE}/scripts/name-fetcher/run.py ${{ inputs.INPUT }} ${{ inputs.OUTPUT }} --force

